"""From-scratch audit: prove that no solver library is linked or included.

1. Parses the import tables of the built binaries (own minimal PE parser, or
   `ldd` on Linux) and checks every imported DLL against an allow-list
   (OS + C/C++ runtime only; the CUDA driver/NVRTC are loaded at runtime with
   LoadLibrary and are deliberately NOT import dependencies).
2. Scans all sources under src/ and include/ for includes or identifiers of
   known solver libraries.
Writes docs/FROM_SCRATCH_AUDIT.md; exit code 1 on any violation.
"""
from __future__ import annotations

import os
import re
import struct
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ALLOW = re.compile(r"^(kernel32|user32|gdi32|advapi32|shell32|ole32|oleaut32|uuid|comdlg32|winspool|ntdll|"
                   r"vcruntime\d+(_1)?|msvcp\d+(_\w+)?|ucrtbase|api-ms-win-.*|libc\.so.*|libm\.so.*|libstdc\+\+.*|"
                   r"libgcc_s.*|libpthread.*|libdl.*|ld-linux.*|linux-vdso.*)(\.dll)?$", re.I)
FORBIDDEN = ["highs", "Highs", "scip", "soplex", "glpk", "cplex", "gurobi", "mosek", "xpress", "clp", "cbc", "coin",
             "osqp", "qpoases", "ipopt", "cuopt", "cupdlp", "pdlp", "ortools", "papilo", "cusparse", "cusolver", "cudss",
             "cholmod", "suitesparse", "umfpack", "mumps", "metis", "amd.h", "Eigen/", "lapack", "blas.h", "mkl"]


def pe_imports(path: Path):
    data = path.read_bytes()
    pe = struct.unpack_from("<I", data, 0x3C)[0]
    assert data[pe:pe + 4] == b"PE\0\0"
    nsec = struct.unpack_from("<H", data, pe + 6)[0]
    opt_size = struct.unpack_from("<H", data, pe + 20)[0]
    opt = pe + 24
    magic = struct.unpack_from("<H", data, opt)[0]
    dd = opt + (112 if magic == 0x20B else 96)
    imp_rva = struct.unpack_from("<I", data, dd + 8)[0]
    secs = []
    for i in range(nsec):
        s = opt + opt_size + 40 * i
        vsize, vaddr, rsize, raddr = struct.unpack_from("<IIII", data, s + 8)
        secs.append((vaddr, max(vsize, rsize), raddr))

    def off(rva):
        for va, sz, ra in secs:
            if va <= rva < va + sz:
                return rva - va + ra
        raise ValueError("rva")

    names = []
    p = off(imp_rva)
    while True:
        name_rva = struct.unpack_from("<I", data, p + 12)[0]
        if name_rva == 0:
            break
        o = off(name_rva)
        names.append(data[o:data.index(b"\0", o)].decode())
        p += 20
    return names


def main():
    build = ROOT / "build"
    bins = [p for p in [build / "pramana.exe", build / "libpramana.dll", build / "pramana_tests.exe",
                        build / "pramana", build / "liblibpramana.so"] if p.exists()]
    lines = ["# From-scratch dependency audit", "",
             "Generated by `bench/audit_deps.py`. PRAMANA links no optimization/solver library and no",
             "linear-algebra library: every algorithm (LU, LDL^T, ordering, simplex, IPM, PDHG, B&B, cuts,",
             "presolve, certifier, CUDA kernels) is in `src/`. The CUDA driver and NVRTC are optional runtime",
             "libraries loaded with LoadLibrary/dlopen (not import dependencies) and contain no solver code.", "",
             "## Imported DLLs of the built binaries", ""]
    bad = 0
    for b in bins:
        try:
            if os.name == "nt":
                imps = pe_imports(b)
            else:
                out = subprocess.run(["ldd", str(b)], capture_output=True, text=True).stdout
                imps = [l.split()[0] for l in out.splitlines() if l.strip()]
        except Exception as e:  # noqa: BLE001
            imps = [f"<parse error {e}>"]
        lines.append(f"- `{b.name}`: " + ", ".join(f"`{i}`" for i in imps))
        for i in imps:
            if not ALLOW.match(i):
                lines.append(f"  - **NOT ALLOWED: {i}**")
                bad += 1
    lines += ["", "## Source scan for solver-library includes / identifiers", ""]
    hits = []
    for f in list((ROOT / "src").rglob("*.*")) + list((ROOT / "include").rglob("*.*")):
        if f.suffix not in (".h", ".hpp", ".cpp", ".cc", ".cu"):
            continue
        for ln, text in enumerate(f.read_text(errors="replace").splitlines(), 1):
            m = re.match(r'\s*#\s*include\s*[<"]([^>"]+)[>"]', text)
            if m and any(k.lower() in m.group(1).lower() for k in FORBIDDEN):
                hits.append(f"{f.relative_to(ROOT)}:{ln}: {text.strip()}")
    if hits:
        lines += [f"- **{h}**" for h in hits]
        bad += len(hits)
    else:
        lines.append("- no include of any solver / sparse-direct / BLAS / LAPACK library found")
    loc = {}
    for f in (ROOT / "src").rglob("*.*"):
        if f.suffix in (".h", ".cpp"):
            mod = f.relative_to(ROOT / "src").parts[0]
            loc[mod] = loc.get(mod, 0) + sum(1 for _ in f.open(errors="replace"))
    lines += ["", "## Lines of code by module (src/)", "", "| module | lines |", "|---|---|"]
    lines += [f"| {k} | {v} |" for k, v in sorted(loc.items(), key=lambda kv: -kv[1])]
    lines += [f"| **total** | **{sum(loc.values())}** |", "", f"Result: {'PASS' if bad == 0 else 'FAIL'} ({bad} violations)"]
    (ROOT / "docs").mkdir(exist_ok=True)
    (ROOT / "docs" / "FROM_SCRATCH_AUDIT.md").write_text("\n".join(lines) + "\n")
    print("\n".join(lines))
    return 1 if bad else 0


if __name__ == "__main__":
    sys.exit(main())
